version: '3.8'

services:
  optivision:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"  # Frontend
      - "8080:8080"  # Backend API
    environment:
      - NODE_ENV=production
    volumes:
      - ./videos:/app/videos  # Mount videos directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/landing.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # For HTTPS certificates
    depends_on:
      - optivision
    restart: unless-stopped

networks:
  default:
    name: optivision-network
