[build]
  publish = "."
  command = "echo 'No build needed - static files'"

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 200

[[redirects]]  
  from = "/app"
  to = "/enhanced_index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
